webConfig:
  defaultServiceInstanceId: manage-service

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 1000ms
  datasource:
    url: jdbc:mysql://localhost:3306/myblog?characterEncoding=utf8&useSSL=false&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: maple
    password: maple
    max-idle: 10
    max-wait: 10000
    initial-size: 5